---
- hosts: sonar-db
  become: yes
  roles:
    - { role: postgresql, db_name: "{{ sonar_db_name }}", db_user: "{{ sonar_db_user }}", db_password: "{{ sonar_db_password }}" }

- hosts: sonar
  become: yes
  roles:
    - { role: java8 }
    - { role: sonar }

- hosts: jenkins
  become: yes
  roles:
    - { role: java8 }
#    - { role: android-sdk }
    - { role: jenkins }
    - { role: jenkins-job, pipeline_name: "hello-world-pipeline", pipeline_git_url: "https://github.com/turneand/hello-world", pipeline_git_branch: "*/jenkins_test" }

- hosts: jenkins-slave
  become: yes
  roles:
    - { role: java8 }
    - { role: jenkins-slave }
