---
jenkins_http_port: 9000
jenkins_prefix_value: jenkins

jenkins_url: "http://localhost:{{ jenkins_http_port }}/{{ jenkins_prefix_value }}"
jenkins_cli_jar: "/var/cache/jenkins/war/WEB-INF/jenkins-cli.jar"
jenkins_cli_cmd: "java -jar {{ jenkins_cli_jar }} -s {{ jenkins_url }}"

pipeline_name: "Pipeline"
pipeline_description: ""
pipeline_poll_schedule: "H/5 * * * *"
pipeline_poll_quiet_period: "5"
pipeline_git_url: ""
pipeline_git_branch: "*/master"
pipeline_git_file: "Jenkinsfile"
