- name: Ensure Sonar repo is installed.
  yum_repository:
    name: sonar
    description: Sonar
    file: sonar
    baseurl: "{{ sonar_rpm_url }}"
    gpgcheck: no

- name: Ensure dependencies are installed.
  package:
    name:
      - sonar
    state: installed
  register: sonar_dependencies_updated

- name: sonar configuration
  lineinfile:
    dest: "{{ sonar_dir }}/conf/sonar.properties"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^#?sonar.web.port=", line: "sonar.web.port={{ sonar_application_port }}" }
    - { regexp: "^#?sonar.jdbc.url=jdbc:postgresql", line: "sonar.jdbc.url=jdbc:postgresql://{{ sonar_db_host }}/{{ sonar_db_name }}" }
    - { regexp: "^#?sonar.jdbc.username=", line: "sonar.jdbc.username={{ sonar_db_user }}" }
    - { regexp: "^#?sonar.jdbc.password=", line: "sonar.jdbc.password={{ sonar_db_password }}" }
    - { regexp: "^#?sonar.web.context=", line: "sonar.web.context=/sonar" }
  register: sonar_config_updated

#- name: download and install the javascript plugin
#  get_url:
#      url: https://sonarsource.bintray.com/Distribution/sonar-javascript-plugin/sonar-javascript-plugin-2.17.0.3154.jar
#      dest: "{{ sonar_dir }}/extensions/plugins"
#  register: sonar_plugin_download

- name: Ensure sonar is definitely running
  service: name=sonar state=started enabled=true
  register: sonar_first_start

- name: Restart if config or dependencies updated and not first run
  service: name=sonar state=restarted enabled=true
  when: sonar_first_start.changed == false and (sonar_config_updated.changed or sonar_dependencies_updated.changed)
